on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.13.4
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Golang module download
      run: go mod download
    - name: Test
      run: bash ./scripts/circle-ci.sh
